name: "Moobile"

exports: "moobile.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools for mobile devices"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Vendor/scroller-iscroll/src/iscroll.js"
  - "Vendor/scroller-zynga/src/Scroller.js"
  - "Vendor/scroller-zynga/src/Animate.js"
  - "Source/Animation/RequestAnimationFrame.js"
  - "Source/Animation/Animation.js"
  - "Source/Browser/Browser.Platform.js"
  - "Source/Core/Core.js"
  - "Source/Class/Class.Instantiate.js"
  - "Source/Component/Component.js"
  - "Source/Control/Control.js"
  - "Source/Control/Button.js"
  - "Source/Control/ButtonGroup.js"
  - "Source/Control/Bar.js"
  - "Source/Control/NavigationBar.js"
  - "Source/Control/Slider.js"
  - "Source/Control/List.js"
  - "Source/Control/ListItem.js"
  - "Source/Control/ActivityIndicator.js"
  - "Source/Control/Image.js"
  - "Source/Control/Text.js"
  - "Source/Control/Tab.js"
  - "Source/Control/TabBar.js"
  - "Source/Dialog/Alert.js"
  - "Source/Element/Element.js"
  - "Source/Element/Element.From.js"
  - "Source/Element/Element.Style.Vendor.js"
  - "Source/Event/EventFirer.js"
  - "Source/Event/Event.Ready.js"
  - "Source/Event/Event.CSS3.js"
  - "Source/Event/Event.Mouse.js"
  - "Source/Event/Event.Tap.js"
  - "Source/Event/Event.Touch.js"
  - "Source/Request/Request.js"
  - "Source/Scroller/Scroller.js"
  - "Source/Scroller/Scroller.IScroll.js"
  - "Source/Scroller/Scroller.Native.js"
  - "Source/Util/Overlay.js"
  - "Source/Types/String.js"
  - "Source/Types/Array.js"
  - "Source/Theme/Theme.js"
  - "Source/View/View.js"
  - "Source/View/ViewSet.js"
  - "Source/View/ViewStack.js"
  - "Source/View/ViewCollection.js"
  - "Source/View/ViewCarousel.js"
  - "Source/View/ViewQueue.js"
  - "Source/View/ScrollView.js"
  - "Source/ViewController/ViewController.js"
  - "Source/ViewController/ViewControllerSet.js"
  - "Source/ViewController/ViewControllerStack.js"
  - "Source/ViewController/ViewControllerStack.Navigation.js"
  - "Source/ViewController/ViewControllerCollection.js"
  - "Source/ViewController/ViewControllerCarousel.js"
  - "Source/ViewController/ViewControllerQueue.js"
  - "Source/ViewTransition/ViewTransition.js"
  - "Source/ViewTransition/ViewTransition.Slide.js"
  - "Source/ViewTransition/ViewTransition.Drop.js"
  - "Source/ViewTransition/ViewTransition.Cover.js"
  - "Source/ViewTransition/ViewTransition.Cover.Box.js"
  - "Source/ViewTransition/ViewTransition.Cover.Page.js"
  - "Source/ViewTransition/ViewTransition.Cubic.js"
  - "Source/ViewTransition/ViewTransition.Drop.js"
  - "Source/ViewTransition/ViewTransition.Fade.js"
  - "Source/ViewTransition/ViewTransition.Flip.js"
  - "Source/ViewTransition/ViewTransition.None.js"
  - "Source/Window/Window.js"
  - "Source/Window/WindowController.js"
